import { ref, readonly } from "vue";
import { useAIStore } from "./useAIStore";
import { AI_WORKER_MESSAGE_TYPES } from "~/utils/constants/pwa";
import type { OutgoingAIMessage } from "~/shared/types/ai-messages";
import { latexToMathjsFull } from "~/utils/math/latexToMathjs";

export function useLocalMathRecognition() {
  type Rect = { minX: number; minY: number; maxX: number; maxY: number };
  type Stroke = { x: number[]; y: number[]; t: number[]; id: number };

  const { $aiWorker } = useNuxtApp();
  const store = useAIStore("global-ai-store");
  const modelId = "datalab-to/chandra";
  const task = "image-to-text" as const;

  const isRecognizing = ref(false);
  const currentLatex = ref<string | null>(null);
  const currentResult = ref<string | null>(null);
  const recognitionError = ref<Error | null>(null);

  const isDownloading = store.isModelDownloading(modelId);
  const progress = store.getModelProgress(modelId);
  const isReady = store.isModelReady(modelId);

  // ── Math scope (persists across strokes) ──
  let _parser: { evaluate: (expr: string) => any; getAll: () => Record<string, unknown> } | null = null;

  async function getParser() {
    if (_parser) return _parser;
    const { create, all } = await import("mathjs");
    const math = create(all!);
    _parser = math.parser();
    return _parser;
  }

  async function getScope(): Promise<Record<string, unknown>> {
    const parser = await getParser();
    return { ...parser.getAll() };
  }

  async function restoreScope(saved: Record<string, unknown>): Promise<void> {
    const parser = await getParser();
    for (const [key, value] of Object.entries(saved)) {
      try {
        parser.evaluate(`${key} = ${JSON.stringify(value)}`);
      } catch {
        // skip non-assignable values
      }
    }
  }

  const generateRequestId = () => `${task}-${Date.now()}-${Math.random()}`;

  async function strokesToPngBuffer(strokes: Stroke[], width: number, height: number): Promise<ArrayBuffer> {
    const padding = 20;
    const w = Math.max(width + padding * 2, 100);
    const h = Math.max(height + padding * 2, 100);

    const canvas = new OffscreenCanvas(w, h);
    const ctx = canvas.getContext("2d")!;
    
    // Fill white background (crucial for OCR)
    ctx.fillStyle = "white";
    ctx.fillRect(0, 0, w, h);

    ctx.translate(padding, padding);

    ctx.lineWidth = 3.0; // slightly thicker for better recognition
    ctx.lineCap = "round";
    ctx.lineJoin = "round";
    ctx.strokeStyle = "black";
    
    for (const stroke of strokes) {
      if (stroke.x.length < 2) continue;
      ctx.beginPath();
      // Ensure we hit integer-ish coordinates, though not strictly required
      ctx.moveTo(stroke.x[0]!, stroke.y[0]!);
      for (let i = 1; i < stroke.x.length; i++) {
        ctx.lineTo(stroke.x[i]!, stroke.y[i]!);
      }
      ctx.stroke();
    }

    const blob = await canvas.convertToBlob({ type: 'image/png' });
    return await blob.arrayBuffer();
  }

  async function recognizeWithLocalAI(
    strokes: Stroke[],
    rect?: Rect,
    canvasSize?: { width: number; height: number }
  ): Promise<{
    latex: string;
    expression: string;
    result: string | null;
    boundingBox?: Rect;
  }> {
    if (!strokes.length) throw new Error("No strokes provided");

    currentLatex.value = null;
    currentResult.value = null;
    recognitionError.value = null;
    isRecognizing.value = true;

    try {
      // 1. Convert strokes to PNG array buffer
      const width = canvasSize?.width || 500;
      const height = canvasSize?.height || 300;
      const imageBuffer = await strokesToPngBuffer(strokes, width, height);

      // 2. Load model (handled by store wrapper)
      await store.loadModel(modelId, task);

      const requestId = generateRequestId();

      // 3. Inference via worker
      const rawText = await new Promise<string>((resolve, reject) => {
        const timeout = setTimeout(() => {
          reject(new Error("Local math recognition timeout (2 minutes)"));
        }, 2 * 60 * 1000);

        const handler = (event: Event) => {
          const message = (event as CustomEvent<OutgoingAIMessage>).detail;

          if (message.type === AI_WORKER_MESSAGE_TYPES.INFERENCE_COMPLETE && message.data.requestId === requestId) {
            clearTimeout(timeout);
            window.removeEventListener("ai-worker-message", handler);

            // The worker returns { generated_text: "..." } for image-to-text / image-text-to-text
            const result = message.data.result as { generated_text?: string } | string;
            const text = typeof result === "string" ? result : (result?.generated_text || "");
            
            if (!text) reject(new Error("No text generated by local model"));
            else resolve(text);
          } else if (message.type === AI_WORKER_MESSAGE_TYPES.INFERENCE_ERROR && message.data.requestId === requestId) {
            clearTimeout(timeout);
            window.removeEventListener("ai-worker-message", handler);
            reject(new Error(message.data.error || "Inference failed"));
          }
        };

        window.addEventListener("ai-worker-message", handler);

        $aiWorker.postMessage({
          type: AI_WORKER_MESSAGE_TYPES.RUN_INFERENCE,
          data: {
            requestId,
            modelId,
            task,
            input: imageBuffer,
            options: {}, // Let the model use defaults
          },
        });
      });

      console.log("🔍 [useLocalMathRecognition] Raw generated text:", rawText);

      // 4. Clean LaTeX Output
      // Similar to MyScript, strip any unwanted wrapping tags / boundaries
      const cleanedLatex = rawText
        .replace(/\\\[\\\[|\\\]\\\]|\\\[|\\\]|\\\(|\\\)/g, '')
        .replace(/\\right\s*[.|)\]]/g, '')
        .replace(/\\left\s*[.|([]/g, '')
        .replace(/\\right/g, '')
        .replace(/\\left/g, '')
        .trim();

      currentLatex.value = cleanedLatex;
      const expression = latexToMathjsFull(cleanedLatex);

      // 5. Evaluate with Mathjs
      let evalResult: string | null = null;
      try {
        const parser = await getParser();
        const raw = parser.evaluate(expression);
        evalResult = raw != null ? String(raw) : null;
      } catch {
        evalResult = null; // No fallback to API solver here
      }
      currentResult.value = evalResult;

      return {
        latex: cleanedLatex,
        expression,
        result: evalResult,
        boundingBox: rect, // We don't get a refined bounding box from Chandra right now
      };
    } catch (err: any) {
      const error = err instanceof Error ? err : new Error(String(err));
      recognitionError.value = error;
      throw error;
    } finally {
      isRecognizing.value = false;
    }
  }

  return {
    recognizeWithLocalAI,
    getScope,
    restoreScope,
    currentLatex: readonly(currentLatex),
    currentResult: readonly(currentResult),
    isRecognizing: readonly(isRecognizing),
    recognitionError: readonly(recognitionError),
    isDownloading,
    progress,
    isReady,
  };
}
