const themeTokens = [
  {
    name: "--font-sans",
    value: '"Saira", sans-serif',
    comment: "Primary UI font",
  },
  { name: "--radius-sm", value: "0.125rem", comment: "2px" },
  { name: "--radius-md", value: "0.25rem", comment: "4px" },
  { name: "--radius-lg", value: "0.375rem", comment: "6px" },
  { name: "--radius-xl", value: "0.5rem", comment: "8px" },
  { name: "--radius-2xl", value: "0.75rem", comment: "12px" },
  { name: "--radius-full", value: "9999px", comment: "Pills and circles" },
  { name: "--tracking-tighter", value: "-0.04em" },
  { name: "--tracking-tight", value: "-0.025em" },
  { name: "--tracking-normal", value: "0em" },
  { name: "--tracking-wide", value: "0.025em" },
  {
    name: "--font-size-caption",
    value: "0.8125rem",
    comment: "Metadata and captions",
  },
  { name: "--leading-tight", value: "1.25" },
  { name: "--leading-snug", value: "1.375" },
  { name: "--leading-normal", value: "1.5" },
  { name: "--leading-relaxed", value: "1.625" },
  {
    name: "--shadow-card",
    value: "0 1px 3px rgb(0 0 0 / 0.06), 0 1px 2px rgb(0 0 0 / 0.04)",
    comment: "Resting card elevation",
  },
  { name: "--shadow-card-hover", value: "0 8px 30px rgb(0 0 0 / 0.08)" },
  { name: "--shadow-dropdown", value: "0 4px 16px rgb(0 0 0 / 0.12)" },
  { name: "--shadow-modal", value: "0 20px 60px rgb(0 0 0 / 0.15)" },
  {
    name: "--shadow-primary-glow",
    value:
      "0 4px 12px color-mix(in srgb, var(--color-primary) 25%, transparent)",
  },
  {
    name: "--shadow-sheet",
    value: "0 -10px 40px rgb(0 0 0 / 0.2)",
    comment: "Bottom-sheet elevation",
  },
  { name: "--duration-fast", value: "120ms", comment: "Small state changes" },
  {
    name: "--duration-normal",
    value: "200ms",
    comment: "Default interaction motion",
  },
  {
    name: "--duration-slow",
    value: "320ms",
    comment: "Overlays and larger transitions",
  },
  {
    name: "--duration-spring",
    value: "420ms",
    comment: "Springy size/position changes",
  },
  {
    name: "--ease-standard",
    value: "cubic-bezier(0.2, 0, 0, 1)",
    comment: "Default easing",
  },
  {
    name: "--ease-emphasized",
    value: "cubic-bezier(0.2, 0, 0, 1.2)",
    comment: "Small emphasized entrance",
  },
  {
    name: "--ease-spring",
    value: "cubic-bezier(0.32, 1.4, 0.45, 1)",
    comment: "Gentle overshoot",
  },
  {
    name: "--target-min",
    value: "1.5rem",
    comment: "WCAG 2.2 minimum target size",
  },
  { name: "--target-compact", value: "2rem", comment: "Compact controls" },
  {
    name: "--target-touch",
    value: "2.75rem",
    comment: "Preferred touch controls",
  },
  { name: "--z-drawer", value: "40" },
  { name: "--z-modal", value: "50" },
  { name: "--z-popover", value: "60" },
  { name: "--z-toast", value: "70" },
  { name: "--z-tooltip", value: "80" },
  { name: "--space-1", value: "0.25rem", comment: "4px" },
  { name: "--space-2", value: "0.5rem", comment: "8px" },
  { name: "--space-3", value: "0.75rem", comment: "12px" },
  { name: "--space-4", value: "1rem", comment: "16px" },
  { name: "--space-6", value: "1.5rem", comment: "24px" },
  { name: "--space-8", value: "2rem", comment: "32px" },
  { name: "--space-12", value: "3rem", comment: "48px" },
  { name: "--space-16", value: "4rem", comment: "64px" },
];

module.exports = { themeTokens };
