const themeTokens = [
  { name: "--font-sans", value: "\"Saira\", sans-serif", comment: "Primary UI font" },
  { name: "--color-primary", value: "#384998", comment: "Interactive brand actions" },
  { name: "--color-on-primary", value: "#ffffff", comment: "Text and icons on primary fills" },
  { name: "--color-success", value: "#10b981", comment: "Positive and completed states" },
  { name: "--color-warning", value: "#f59e0b", comment: "Caution and due-soon states" },
  { name: "--color-error", value: "#ef4444", comment: "Destructive and failed states" },
  { name: "--color-info", value: "#00c7e4", comment: "Informational states" },
  { name: "--color-secondary", value: "#e7e9ec", comment: "Borders, dividers, neutral chips" },
  { name: "--color-background", value: "#fafafa", comment: "Page background" },
  { name: "--color-surface", value: "#f0f0f2", comment: "Raised surfaces" },
  { name: "--color-surface-subtle", value: "#f4f5f7", comment: "Subtle rows and hover surfaces" },
  { name: "--color-surface-strong", value: "#dddfe5", comment: "Selected and pressed surfaces" },
  { name: "--color-surface-container", value: "var(--color-surface)", comment: "Compatibility surface alias" },
  { name: "--color-content-on-background", value: "#333333", comment: "Text on page background" },
  { name: "--color-content-on-surface", value: "#575252", comment: "Text on card/panel surfaces" },
  { name: "--color-content-on-surface-strong", value: "#333333", comment: "Strong text on surfaces" },
  { name: "--color-content-secondary", value: "#6b7280", comment: "Metadata and secondary text" },
  { name: "--color-content-disabled", value: "#9ca3af", comment: "Disabled and placeholder text" },
  { name: "--color-white", value: "#ffffff", comment: "Compatibility white token" },
  { name: "--color-dark", value: "#1f2937", comment: "Compatibility dark text token" },
  { name: "--color-border", value: "var(--color-secondary)", comment: "Default border" },
  { name: "--color-border-secondary", value: "var(--color-secondary)", comment: "Compatibility border alias" },
  { name: "--color-primary-50", value: "color-mix(in srgb, var(--color-primary) 10%, transparent)", comment: "Primary subtle fill" },
  { name: "--radius-sm", value: "0.125rem", comment: "2px" },
  { name: "--radius-md", value: "0.25rem", comment: "4px" },
  { name: "--radius-lg", value: "0.375rem", comment: "6px" },
  { name: "--radius-xl", value: "0.5rem", comment: "8px" },
  { name: "--radius-2xl", value: "0.75rem", comment: "12px" },
  { name: "--tracking-tighter", value: "-0.04em" },
  { name: "--tracking-tight", value: "-0.025em" },
  { name: "--tracking-normal", value: "0em" },
  { name: "--tracking-wide", value: "0.025em" },
  { name: "--leading-tight", value: "1.25" },
  { name: "--leading-snug", value: "1.375" },
  { name: "--leading-normal", value: "1.5" },
  { name: "--leading-relaxed", value: "1.625" },
  { name: "--line-height-tight", value: "var(--leading-tight)", comment: "Compatibility typography alias" },
  { name: "--line-height-normal", value: "var(--leading-normal)", comment: "Compatibility typography alias" },
  { name: "--line-height-relaxed", value: "var(--leading-relaxed)", comment: "Compatibility typography alias" },
  { name: "--shadow-card-hover", value: "0 8px 30px rgb(0 0 0 / 0.08)" },
  { name: "--shadow-dropdown", value: "0 4px 16px rgb(0 0 0 / 0.12)" },
  { name: "--shadow-modal", value: "0 20px 60px rgb(0 0 0 / 0.15)" },
  { name: "--shadow-primary-glow", value: "0 4px 12px rgb(56 73 152 / 0.25)" },
  { name: "--shadow-glass", value: "0 24px 64px -8px rgb(0 0 0 / 0.18)", comment: "Compatibility glass panel shadow" },
  { name: "--space-1", value: "0.25rem", comment: "4px" },
  { name: "--space-2", value: "0.5rem", comment: "8px" },
  { name: "--space-3", value: "0.75rem", comment: "12px" },
  { name: "--space-4", value: "1rem", comment: "16px" },
  { name: "--space-6", value: "1.5rem", comment: "24px" },
  { name: "--space-8", value: "2rem", comment: "32px" },
  { name: "--space-12", value: "3rem", comment: "48px" },
  { name: "--space-16", value: "4rem", comment: "64px" },
];

const rootTokens = [
  { name: "--ui-container", value: "var(--container-8xl)" },
  { name: "--ui-primary", value: "var(--color-primary)" },
  { name: "--ui-bg", value: "var(--color-background)" },
  { name: "--ui-bg-muted", value: "var(--color-surface-subtle)" },
  { name: "--ui-bg-accented", value: "var(--color-surface-strong)" },
  { name: "--ui-text", value: "var(--color-content-on-background)" },
  { name: "--ui-text-muted", value: "var(--color-content-secondary)" },
  { name: "--ui-border", value: "var(--color-secondary)" },
  { name: "--ds-brand-gradient", value: "linear-gradient(90deg, rgb(49 165 217) 0%, rgb(248 54 145) 46%, rgb(255 184 0) 100%)" },
  { name: "--ds-focus-outline-color", value: "var(--color-info)" },
  { name: "--ds-backdrop-strong", value: "rgb(2 6 23 / 0.8)" },
  { name: "--ds-backdrop-dim", value: "rgb(0 0 0 / 0.4)" },
  { name: "--component-card-radius", value: "var(--radius-2xl)" },
  { name: "--component-card-padding-xs", value: "var(--space-1)" },
  { name: "--component-card-padding-sm", value: "var(--space-2)" },
  { name: "--component-card-padding-md", value: "var(--space-3)" },
  { name: "--component-card-padding-lg", value: "var(--space-4)" },
  { name: "--component-card-padding-xl", value: "calc(var(--space-4) + var(--space-1))" },
  { name: "--component-toast-shadow", value: "var(--shadow-modal)" },
  { name: "--component-drawer-shadow", value: "var(--shadow-dropdown)" },
  { name: "--component-dialog-shadow", value: "var(--shadow-modal)" },
];

const legacyAliasTokens = [
  { name: "--margin-xs", value: "var(--space-1)" },
  { name: "--margin-sm", value: "var(--space-2)" },
  { name: "--margin-md", value: "var(--space-4)" },
  { name: "--margin-lg", value: "var(--space-6)" },
  { name: "--margin-xl", value: "var(--space-8)" },
  { name: "--margin-2xl", value: "calc(var(--space-8) + var(--space-4))" },
  { name: "--padding-xs", value: "var(--space-1)" },
  { name: "--padding-sm", value: "var(--space-2)" },
  { name: "--padding-md", value: "var(--space-4)" },
  { name: "--padding-lg", value: "var(--space-6)" },
  { name: "--padding-xl", value: "var(--space-8)" },
  { name: "--padding-2xl", value: "calc(var(--space-8) + var(--space-4))" },
  { name: "--spacing-xs", value: "var(--space-1)" },
  { name: "--spacing-sm", value: "var(--space-2)" },
  { name: "--spacing-md", value: "var(--space-4)" },
  { name: "--spacing-lg", value: "var(--space-6)" },
  { name: "--spacing-xl", value: "var(--space-8)" },
];

const componentTokenNames = [
  "button",
  "input",
  "toast",
  "drawer",
  "card",
  "note-row",
  "editor",
  "menu",
  "modal",
];

module.exports = {
  componentTokenNames,
  legacyAliasTokens,
  rootTokens,
  themeTokens,
};
