const themeTokens = [
  {
    name: "--color-primary",
    value: "#051a39",
    comment: "Interactive brand actions",
  },
  {
    name: "--color-on-primary",
    value: "#ffffff",
    comment: "Text and icons on primary fills",
  },
  { name: "--color-success", value: "#10b981" },
  { name: "--color-warning", value: "#f59e0b" },
  { name: "--color-error", value: "#ef4444" },
  { name: "--color-info", value: "#00c7e4" },
  { name: "--color-success-text", value: "#047857" },
  { name: "--color-warning-text", value: "#92400e" },
  { name: "--color-error-text", value: "#b91c1c" },
  { name: "--color-info-text", value: "#0369a1" },
  { name: "--color-secondary", value: "#e7e9ec" },
  { name: "--color-background", value: "#fafafa" },
  { name: "--color-surface", value: "#f0f0f2" },
  { name: "--color-surface-subtle", value: "#f4f5f7" },
  { name: "--color-surface-strong", value: "#dddfe5" },
  { name: "--color-content-on-background", value: "#333333" },
  { name: "--color-content-on-surface", value: "#575252" },
  { name: "--color-content-on-surface-strong", value: "#333333" },
  { name: "--color-content-secondary", value: "#606771" },
  { name: "--color-content-disabled", value: "#6b7280" },
  {
    name: "--color-white",
    value: "#ffffff",
    comment: "Compatibility white token",
  },
  {
    name: "--color-dark",
    value: "#1f2937",
    comment: "Compatibility dark text token",
  },
  { name: "--color-border", value: "var(--color-secondary)" },
  {
    name: "--color-primary-soft",
    value: "color-mix(in srgb, var(--color-primary) 10%, transparent)",
  },
  {
    name: "--color-primary-hover",
    value: "color-mix(in srgb, black 10%, var(--color-primary))",
  },
  {
    name: "--color-primary-active",
    value: "color-mix(in srgb, black 18%, var(--color-primary))",
  },
  { name: "--color-on-success", value: "#043a28" },
  { name: "--color-on-error", value: "#ffffff" },
  { name: "--color-border-strong", value: "#c7cbd2" },
  { name: "--color-accent-blue", value: "#3b82f6" },
  { name: "--color-accent-indigo", value: "#6366f1" },
  { name: "--color-accent-purple", value: "#8b5cf6" },
  { name: "--color-accent-pink", value: "#ec4899" },
  { name: "--color-accent-rose", value: "#f43f5e" },
  { name: "--color-accent-teal", value: "#06b6d4" },
  { name: "--color-accent-cyan", value: "#00e2ff" },
  { name: "--color-accent-orange", value: "#f97316" },
];

const darkTokens = [
  { name: "--color-background", value: "#0f1216" },
  { name: "--color-surface", value: "#171b21" },
  { name: "--color-surface-subtle", value: "#1e232b" },
  { name: "--color-surface-strong", value: "#2b313b" },
  { name: "--color-content-on-background", value: "#e9ebef" },
  { name: "--color-content-on-surface", value: "#c2c7d0" },
  { name: "--color-content-on-surface-strong", value: "#f3f5f8" },
  { name: "--color-content-secondary", value: "#99a1ad" },
  { name: "--color-content-disabled", value: "#8b95a1" },
  { name: "--color-secondary", value: "#2b313b" },
  { name: "--color-border-strong", value: "#3a4250" },
  {
    name: "--color-primary",
    value: "#e8e9f2",
    comment: "Accepted dark primary",
  },
  {
    name: "--color-primary-hover",
    value: "color-mix(in srgb, white 10%, var(--color-primary))",
  },
  {
    name: "--color-primary-active",
    value: "color-mix(in srgb, white 18%, var(--color-primary))",
  },
  { name: "--color-on-primary", value: "#0f1216" },
  { name: "--color-success-text", value: "#34d399" },
  { name: "--color-warning-text", value: "#fbbf24" },
  { name: "--color-error-text", value: "#f87171" },
  { name: "--color-info-text", value: "#38bdf8" },
];

module.exports = { themeTokens, darkTokens };
