// -----------------------------------------------------------------------------
// This file is auto-generated by scripts/build-icon-sprite.ts
// Do not edit this file manually.
// -----------------------------------------------------------------------------

/** Public URL of the icon sprite. Precached by the service worker. */
export const ICON_SPRITE_URL = '/icons.svg'

/** Content hash of the sprite, for debugging which build a client is running. */
export const ICON_SPRITE_HASH = '09d374f3'
