import { existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs'
import { basename, extname, resolve } from 'node:path'

const iconsDir = resolve(process.cwd(), 'app/assets/icons')
const outputDir = resolve(process.cwd(), 'app/utils')
const outputFile = resolve(outputDir, 'icons.generated.ts')

function toPascalCase(value: string) {
  return value
    .replace(/[-_]+/g, ' ')
    .replace(/\s+(.)/g, (_, char: string) => char.toUpperCase())
    .replace(/^(.)/, (_, char: string) => char.toUpperCase())
    .replace(/\s/g, '')
}

function assertIconsDirExists() {
  console.log(`Checking icons directory: ${iconsDir}`)
  if (!existsSync(iconsDir)) {
    throw new Error(`Icons directory does not exist: ${iconsDir}`)
  }
}

function ensureOutputDirExists() {
  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true })
  }
}

assertIconsDirExists()
ensureOutputDirExists()

const iconNames = readdirSync(iconsDir)
  .filter((file) => file.endsWith('.svg'))
  .map((file) => basename(file, extname(file)))
  .sort((a, b) => a.localeCompare(b))

const iconArray = iconNames.map((name) => `  '${name}',`).join('\n')

const iconObject = iconNames
  .map((name) => `  ${toPascalCase(name)}: '${name}',`)
  .join('\n')

const content = `// -----------------------------------------------------------------------------
// This file is auto-generated by scripts/generate-icons.ts
// Do not edit this file manually.
// -----------------------------------------------------------------------------

export const ICON_NAMES = [
${iconArray}
] as const

export type IconName = typeof ICON_NAMES[number]

export const IconName = {
${iconObject}
} as const

export type IconNameKey = keyof typeof IconName
`

writeFileSync(outputFile, content)

console.log(`Generated ${iconNames.length} icon name${iconNames.length === 1 ? '' : 's'}.`)